// GuessingGame.Gui.React/ClientApp/src/components/Home.js
import React, { Component } from 'react';

export class Home extends Component {
  displayName = Home.name

    constructor(props) {
        super(props);
        this.state = { number: '', message: '', logs: [], gameOver: false }
        this.HandleChange = this.HandleChange.bind(this);
        this.CheckNumber = this.CheckNumber.bind(this);
        this.HandleKeyPress = this.HandleKeyPress.bind(this);
        this.ShowLogs = this.ShowLogs.bind(this);
        this.PlayAgain = this.PlayAgain.bind(this);
    }

    CheckNumber() {
        fetch(`api/checknumber?number=${this.state.number}`)
            .then(response => response.json())
            .then(response => {
                this.setState({ message: response['content'], number: '' });
                if (this.state.message.includes('Correct!')) {
                    document.getElementById('ShowLogsButton').hidden = false;
                    document.getElementById('PlayAgainButton').hidden = false;
                }
            });
    }

    ShowLogs() {
        fetch('api/showlogs')
            .then(response => response.json())
            .then(response => {
                this.setState({ logs: response['content']});
            });
        this.state.message = '';
        document.getElementById('InputBox').disabled = true;
        document.getElementById('ShowLogsButton').hidden = true;
        document.getElementById('CheckNumberButton').hidden = true;
    }

    PlayAgain() {
        window.location.reload();
    }

    HandleChange(e) {
        this.setState({ number: e.target.value });
    }

    HandleKeyPress(e) {
        if (e.key === 'Enter') {
            this.CheckNumber();
        }
    }

  render() {
      return (
          <div>
              <label>Guess my number:</label><br/>
              <input id="InputBox" type="number" value={this.state.number}
      placeholder="Good luck!" onChange={this.HandleChange} autoFocus
                  onKeyPress={this.HandleKeyPress}/><br />
              <button id="CheckNumberButton" onClick={this.CheckNumber}>Check</button><br />
              <p>{this.state.message}</p>
              <button id="ShowLogsButton" onClick={this.ShowLogs} hidden>Show Logs</button><br />
              <div>{this.state.logs}</div>
              <div>
                  <button id="PlayAgainButton" onClick={this.PlayAgain} hidden>Play Again</button>
            </div>
          </div>
    );
}
}

// GuessingGame.Gui.Angular/ClientApp/src/app/home/home.component.ts
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
})
export class HomeComponent {
  private Number: number;
  private Message: string;
  private Logs: string[];
  private GameOver: boolean;
  private Http: HttpClient;

  constructor(private http: HttpClient) {
    this.http = http;
  }

  public CheckNumber(): void {
    if (!this.IsValid(this.Number)) return;
    this.http.get<GameResponse>('http://localhost:5000/api/checknumber?number=' + this.Number).subscribe((data: GameResponse) => {
      this.Number = undefined;
      var inputBox = document.getElementById('InputBox');
      inputBox.setAttribute('placeholder', 'Try again!');
      this.Message = data['content'];
      if (this.Message.includes('Correct!')) {
        inputBox.setAttribute('placeholder', 'Congratulations!');
        this.GameOver = true;
        inputBox.setAttribute('disabled', 'true');
      }
    });
  }

  public ShowLogs(): void {
    this.http.get<GameResponse>('http://localhost:5000/api/showlogs').subscribe((data: GameResponse) => {
      this.Logs = data['content'].split('\r\n');
    });
  }

  public PlayAgain(): void {
    location.reload();
  }

  private IsValid(number: number): boolean {
    if (Math.abs(this.Number) > 2147483647 || this.Number == null) { 
      this.Message = 'Invalid number';
      return false;
    }
    return true;
  }
}

interface GameResponse {
  content: string;
}

<div>
  <label>Guess my number:</label><br>
  <input id="InputBox" type="number" (keyup.enter)="CheckNumber()" [(ngModel)]="Number" placeholder="Good luck!" autofocus>
</div>

<div *ngIf="!GameOver">
  <button (click)="CheckNumber()">Check</button>
  <p *ngIf="Message">{{Message}}</p>
</div>

<div *ngIf="GameOver">
  <button (click)="ShowLogs()">Show Log</button>
  <p *ngFor="let Log of Logs">{{Log}}</p>
</div>

<div *ngIf="GameOver">
  <button (click)="PlayAgain()">Play again?</button>
</div>
